comment:
  header: Hi ğŸ‘‹ğŸ¾, there you earthlings ğŸ‘©ğŸ½â€ğŸŒ¾ ğŸ‘¨ğŸ¿â€ğŸŒ¾ ğŸ„ ğŸ– ğŸ¦ƒ
  footer: "\
    ---\n\n\
    > This is an automated comment created by the 'Label Commenter ğŸ·' action."

labels:
  - name: mvpr ğŸŒ®
    labeled:
      pr:
        body: |
          ğŸ· ( MVPR ğŸŒ® )
          You 'nantli' ğŸ‘¨ğŸ¿â€ğŸŒ¾ deserve a vegan taco ğŸŒ®!

          Your effort is very much appreciated, please someone in here type '/ghipy Have a taco! in a comment'
  - name: "locked: resolved âœ…"
    labeled:
      issue:
        body: |
          ğŸ· ( locked: resolved âœ… )
          This issue has been **LOCKED** because of it being resolved ğŸ‘©ğŸ½â€ğŸŒ¾!

          The issue has been fixed and is therefore considered resolved.
          If you still encounter this or it has changed, open a new issue instead of responding to solved ones.
        action: close
        locking: lock
        lock_reason: resolved
  - name: "locked: heated ğŸ§¯"
    labeled:
      issue:
        body: |
          ğŸ· ( locked: heated ğŸ§¯ )
          This issue has been **LOCKED** because of heated conversation ğŸ§¯!

          We appreciate exciting conversations, as long as they won't become too aggressive and/or emotional.
        locking: lock
        lock_reason: too heated
      pr:
        body: |
          ğŸ· ( locked: heated ğŸ§¯ )
          This pull-request has been **LOCKED** because of heated conversation ğŸ§¯!

          We appreciate exciting conversations, as long as they won't become too aggressive and/or emotional.
        locking: lock
        lock_reason: too heated
    unlabeled:
      issue:
        body: |
          Unlabeled -> ğŸ· ( locked: heated ğŸ§¯ )
          This issue has been unlocked now ğŸ–.
        locking: unlock
      pr:
        body: |
          Unlabeled -> ğŸ· ( locked: heated ğŸ§¯ )
          This pull-request has been unlocked now ğŸ–.
        locking: unlock
  - name: "locked: spam ğŸ‘®ğŸ»â€â™‚ï¸"
    labeled:
      issue:
        body: |
          ğŸ· ( locked: spam ğŸ‘®ğŸ»â€â™‚ï¸ )
          This issue has been **LOCKED** because of spam ğŸ™Š!

          Please do not spam messages and/or issues on the issue tracker. You may get blocked from this repository for doing so.
        action: close
        locking: lock
        lock_reason: spam
      pr:
        body: |
          ğŸ· ( locked: spam ğŸ‘®ğŸ»â€â™‚ï¸ )
          This pull-request has been **LOCKED** because of spam ğŸ™Š!

          Please do not spam messages and/or pull-requests on this project. You may get blocked from this repository for doing so.
        action: close
        locking: lock
        lock_reason: spam
  - name: proposal âœ¨
    labeled:
      issue:
        body: |
          ğŸ· ( proposal âœ¨ )
          Thank you @{{ issue.user.login }} for suggesting this ğŸ„.

          We really appreciate your time and help ğŸ«¶ğŸ¾.
  - name: "locked: breaking ğŸ’¥"
    labeled:
      issue:
        body: |
          ğŸ· ( locked: breaking ğŸ’¥ )
          This issue has been **LOCKED** because of breaking changes ğŸ’©!

          We appreciate exciting contributions, as long as they don't break anything.
        locking: lock
        lock_reason: breaking changes
      pr:
        body: |
          ğŸ· ( locked: breaking ğŸ’¥ )
          This pull-request has been **LOCKED** because of breaking changes ğŸ’©!

          We appreciate exciting contributions, as long as they don't break anything.
        locking: lock
        lock_reason: breaking changes
    unlabeled:
      issue:
        body: |
          Unlabeled -> ğŸ· ( locked: breaking ğŸ’¥ )
          This issue has been unlocked now ğŸ–.
        locking: unlock
      pr:
        body: |
          Unlabeled -> ğŸ· ( locked: breaking ğŸ’¥ )
          This pull-request has been unlocked now ğŸ–.
        locking: unlock
  - name: duplicate ğŸ‘¯â€â™‚ï¸
    labeled:
      issue:
        body: |
          ğŸ· ( duplicate ğŸ‘¯â€â™‚ï¸ )
          We really appreciate your time and help, but this issue already exists ğŸ«.
        action: close
  - name: "effort: 1ï¸âƒ£3ï¸âƒ£"
    labeled:
      issue:
        body: |
          ğŸ· ( effort: 1ï¸âƒ£3ï¸âƒ£ )
          Bring the pop corn ğŸ¿!

          Please someone throw to these brave earthlings a '/giphy machete' or '/giphy you have my sword', or something better maybe, in the comments.          
          Let's show some love and respect ğŸ¦ƒ!
      pr:
        body: |
          ğŸ· ( effort: 1ï¸âƒ£3ï¸âƒ£ )
          What a team of legends ğŸ«¶ğŸ»!

          Please someone throw to these brave earthlings a '/giphy machete' or '/giphy you have my sword', or something better maybe, in the comments.          
          Let's show some love and respect ğŸ¦ƒ!
  - name: good first issue ğŸ‘‘
    labeled:
      issue:
        body: |
          ğŸ· ( good first issue ğŸ‘‘ )
          This issue is easy for contributing. Everyone can work on this ğŸ„ ğŸ– ğŸ¦ƒ.

          Here at @nantli we are a group of friends wanting to create awereness of animal rights while learning and sharing thechnology ğŸ‘©ğŸ½â€ğŸŒ¾ ğŸ‘©ğŸ¼â€ğŸ’».
          Visit our website [Nantli](https://nantli.xyz) and be kind to animals ğŸ·!
  - name: "help wanted ğŸ™ğŸ¾"
    labeled:
      issue:
        body: |
          ğŸ· ( help wanted ğŸ™ğŸ¾ )
          Hello, anybody out there ğŸ‘€ ?

          Any help would be very much appreciated ğŸ§. Maybe a '/ghipy help!' on the comments could do something ğŸ¦©.
      pr:
        body: |
          ğŸ· ( help wanted ğŸ™ğŸ¾ )
          Hello, anybody out there ğŸ‘€ ?

          Any help would be very much appreciated ğŸ§. Maybe a '/ghipy help!' on the comments could do something ğŸ¦©.
  - name: invalid ğŸ™Š
    labeled:
      issue:
        body: |
          ğŸ· ( invalid ğŸ™Š )
          Please follow the issue templates ğŸˆ.
        action: close
      pr:
        body: |
          ğŸ· ( invalid ğŸ™Š )
          Thank you @{{ pull_request.user.login }} for suggesting this. Please follow the pull request templates ğŸˆ.
        action: close
    unlabeled:
      issue:
        body: |
          Unlabeled -> ğŸ· ( invalid ğŸ™Š )
          Thank you for following the template. The repository owner will reply ğŸ¦¬.
        action: open
  - name: wontfix ğŸ§Œ
    labeled:
      issue:
        body: |
          ğŸ· ( wontfix ğŸ§Œ )
          This will not be worked on but we appreciate your contribution ğŸ¦™.
        action: close
    unlabeled:
      issue:
        body: |
          ğŸ· ( wontfix ğŸ§Œ )
          This has become active again ğŸ–.
        action: open
  - name: "work: clear ğŸ¥±"
    labeled:
      issue:
        body: |
          ğŸ· ( work: clear ğŸ¥± )
          In "clear" contexts, your options are obvious, clear and cause-and-effect relationships are apparent to everyone involved.

          Here, there are often explicit steps in place that dictate the next stage of the process.
      pr:
        body: |
          ğŸ· ( work: clear ğŸ¥± )
          In "clear" contexts, your options are obvious, clear and cause-and-effect relationships are apparent to everyone involved.

          Here, there are often explicit steps in place that dictate the next stage of the process.
  - name: "work: complicated ğŸ˜¬"
    labeled:
      issue:
        body: |
          ğŸ· ( work: complicated ğŸ˜¬ )
          "Complicated" problems might have several "correct" solutions. Here, there is a clear relationship between cause and effect, but it may not be visible to everyone, because the problem is... complicated. 

          The decision-making approach here is to "Sense then Analyze then Respond." In other words, you need to assess the situation, analyze what is known (often with the help of experts), and decide on the best response, using good practice.
      pr:
        body: |
          ğŸ· ( work: complicated ğŸ˜¬ )
          "Complicated" problems might have several "correct" solutions. Here, there is a clear relationship between cause and effect, but it may not be visible to everyone, because the problem is... complicated. 

          The decision-making approach here is to "Sense then Analyze then Respond." In other words, you need to assess the situation, analyze what is known (often with the help of experts), and decide on the best response, using good practice.
  - name: "work: complex ğŸ˜³"
    labeled:
      issue:
        body: |
          ğŸ· ( work: complex ğŸ˜³ )
          It might be impossible to identify one "correct" solution, or spot cause-and-effect relationships, in "complex" situations.

          Complex contexts are often unpredictable, and the best approach here is to "Probe then Sense then Respond." Rather than trying to control the situation or insisting on a plan of action, it's often best to be patient, look for patterns, and encourage a solution to emerge.
      pr:
        body: |
          ğŸ· ( work: complex ğŸ˜³ )
          It might be impossible to identify one "correct" solution, or spot cause-and-effect relationships, in "complex" situations.

          Complex contexts are often unpredictable, and the best approach here is to "Probe then Sense then Respond." Rather than trying to control the situation or insisting on a plan of action, it's often best to be patient, look for patterns, and encourage a solution to emerge.
  - name: "work: chaotic ğŸ˜±"
    labeled:
      issue:
        body: |
          ğŸ· ( work: chaotic ğŸ˜± )
          In "chaotic" situations, no relationship between cause and effect exists, so your primary goal is to establish order and stability. Crisis and emergency scenarios often fall into this domain.

          The decision-making approach here is to "Act then Sense then Respond." You need to act decisively to address the most pressing issues, sense where there is stability and where there isn't, and then respond to move the situation from chaos to complexity.
      pr:
        body: |
          ğŸ· ( work: chaotic ğŸ˜± )
          In "chaotic" situations, no relationship between cause and effect exists, so your primary goal is to establish order and stability. Crisis and emergency scenarios often fall into this domain.

          The decision-making approach here is to "Act then Sense then Respond." You need to act decisively to address the most pressing issues, sense where there is stability and where there isn't, and then respond to move the situation from chaos to complexity.
  - name: "type: hotfix ğŸš‘"
    labeled:
      issue:
        body: |
          ğŸ· ( type: hotfix ğŸš‘ )
          Whe need 'nantli' ğŸ‘¨ğŸ¿â€ğŸŒ¾ help, now!

          But please someone put a '/giphy everything is fine' in the comments, so everyone can see that we 'nantlis' always do just fine, under any circunstances ğŸ«£.
      pr:
        body: |
          ğŸ· ( type: hotfix ğŸš‘ )
          To the rescue ğŸ‘¨ğŸ¿â€ğŸŒ¾ !

          But please someone put a '/giphy we are just fine' in the comments, so everyone can see that we 'nantlis' always do just fine, under any circunstances ğŸ«£.
